name: GFSLT-VLP
data:
  train_label_path: ./data/Phonexi-2014T/SI_labels.train
  dev_label_path: ./data/Phonexi-2014T/SI_labels.dev
  test_label_path: ./data/Phonexi-2014T/SI_labels.test
  img_path: /mnt/c/Research/Dataset/phoenix-2014_o/PHOENIX-2014-T-release-v3/PHOENIX-2014-T/features/fullFrame-210x260px/
  max_length: 300
training:
  wandb: disabled # online or disabled
  scale_embedding: False
model:
  tokenizer: ./pretrain_models/MBart_trimmed
  transformer:  ./pretrain_models/MBart_trimmed
  visual_encoder: ./pretrain_models/mytran
  sign_proj: True